Adding tests for buck lint. (#348)

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,7 +23,19 @@ before_script:
 script:
   - SKIP_OKBUCK= ./buckw --version
   - ./buckw targets --type android_binary java_test groovy_test robolectric_test | xargs ./buckw build
-  - ./buckw targets --type genrule | xargs ./buckw build
+  - ./buckw targets --type genrule | grep -v lintErrorLibrary | xargs ./buckw build
+  - ./buckw build //libraries/lintErrorLibrary:lint_debug;
+    if [ $? -eq 0 ]; then
+      echo "Lint passed when it should have failed. Please revisit any changes you may have made to lint wiring.";
+      exit 1;
+    else
+      if grep -q 'id=\"DontUseSystemTime\"' 'buck-out/gen/libraries/lintErrorLibrary/lint_debug/lint_debug_out/lint-results.xml'; then
+        echo "Lint failed as expected.";
+      else
+        echo "Lint did not create the expected output. Please double check your changes to resolve.";
+        exit 1;
+      fi
+    fi
   - ./buckw test --include unit
   - android-wait-for-emulator
   - adb shell input keyevent 82
