Android Lint Support (#228)
- Adds support for generating `lint_*` `genrule`s for `android_library` targets
- Hooks are in place to let lint rules be generated for any jvm library targets. Theoretically lint can be run on java, kotlin or scala etc with some small tweaks. Lint can also be run on test sources with a few small tweaks as well. These changes will be part of a subsequent PR
- Supports custom lint jars embedded in aars
- Supports custom lint project/external dependencies. For example, a java library that defines custom lint rules can be added to another library as a linter by making it a dependency of the `buckLint` configuration
- Fully incremental, parallel and buck cache/network cache friendly
- Supports many android dsl options specified in `lintOptions`
- Ability to pin lint api version and not be surprised when android gradle plugin pulls in new checks on updates
- Requires an updated `buckw` by running the `buckWrapper` to watch for changes to `lint.xml` files and run `okbuck` again as needed
- Lint on all android rules can be run like `buck query "filter('lint_*', kind('genrule', '//...'))" | xargs buck build`

diff --git a/buckw b/buckw
--- a/buckw
+++ b/buckw
@@ -4,7 +4,7 @@
 ##
 ##  Buck wrapper script to invoke okbuck when needed, before running buck
 ##
-##  Created by OkBuck Gradle Plugin on : Mon Oct 10 12:58:03 PDT 2016
+##  Created by OkBuck Gradle Plugin on : Sun Nov 06 00:35:21 PDT 2016
 ##
 #########################################################################
 
@@ -93,7 +93,8 @@ getChanges ( ) {
         ["anyof",
             ["imatch", "**/*.gradle", "wholename"],
             ["imatch", "**/src/**/AndroidManifest.xml", "wholename"],
-            ["imatch", "**/gradle-wrapper.properties", "wholename"]
+            ["imatch", "**/gradle-wrapper.properties", "wholename"],
+            ["imatch", "**/lint.xml", "wholename"]
         ]
     ],
     "fields": ["name"]
@@ -128,11 +129,12 @@ runOkBuck ( ) {
     if [[ ! -z "$INSTALLED_WATCHMAN" ]]; then
         getToClean | jsonq '"\n".join(obj["files"])' | xargs rm
         info "DELETED OLD BUCK FILES"
-        EXTRA_ARGS="-xokbuckClean"
+        EXTRA_OKBUCK_ARGS="-xokbuckClean $EXTRA_OKBUCK_ARGS"
     fi
 
     rm -f $OKBUCK_SUCCESS
-    ( $WORKING_DIR/gradlew -p $WORKING_DIR okbuck -Dokbuck.wrapper=true $EXTRA_ARGS --stacktrace && updateOkBuckSuccess && success "PROCEEDING WITH BUCK" ) || die "OKBUCK FAILED"
+    ( $WORKING_DIR/gradlew -p $WORKING_DIR okbuck -Dokbuck.wrapper=true $EXTRA_OKBUCK_ARGS --stacktrace &&
+    updateOkBuckSuccess && success "PROCEEDING WITH BUCK" ) || die "OKBUCK FAILED"
 }
 
 watchmanWorkflow ( ) {
