Add some error handling for git failures in buckw

diff --git a/buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE b/buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
--- a/buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
+++ b/buildSrc/src/main/resources/com/uber/okbuck/core/util/wrapper/BUCKW_TEMPLATE
@@ -140,7 +140,7 @@ setupBuckBinary ( ) {
         # Install buck from source if not already available
         if [[ ! -d "$BUCK_HOME" ]]; then
             warn "BUCK NOT FOUND IN '$BUCK_HOME'. INSTALLING BUCK..."
-            git clone $DEFAULT_BUCK_REPO $BUCK_HOME
+            git clone $DEFAULT_BUCK_REPO $BUCK_HOME || die "FAILED TO CLONE $DEFAULT_BUCK_REPO"
         fi
 
         # Add custom buck remote
@@ -148,7 +148,7 @@ setupBuckBinary ( ) {
             cd $BUCK_HOME
             REMOTE_EXISTS=$(git remote -v | grep "$CUSTOM_REMOTE_NAME")
             if [[ -z "$REMOTE_EXISTS" ]]; then
-                git remote add $CUSTOM_REMOTE_NAME $CUSTOM_BUCK_REPO
+                git remote add $CUSTOM_REMOTE_NAME $CUSTOM_BUCK_REPO || die "FAILED TO ADD REMOTE $CUSTOM_BUCK_REPO"
             fi
             cd -
         fi
@@ -160,7 +160,7 @@ setupBuckBinary ( ) {
             CURRENT_BUCK_VERSION=$(git rev-parse HEAD)
             if [[ "$BUCK_VERSION" != "$CURRENT_BUCK_VERSION" ]]; then
                 info "BUCK VERSION IS AT $CURRENT_BUCK_VERSION , BUT IT SHOULD BE $BUCK_VERSION. UPDATING BUCK"
-                git clean -fdx --quiet && git reset --hard --quiet && git fetch --all && git checkout "$BUCK_VERSION" --quiet
+                git clean -fdx --quiet && git reset --hard --quiet && git fetch --all && git checkout "$BUCK_VERSION" --quiet && success "UPDATED BUCK TO $BUCK_VERSION" || die "FAILED TO UPDATE BUCK TO $BUCK_VERSION"
             fi
             popd >/dev/null
         fi
